version: "3.8"

x-build-cdn-server: &x-build-cdn-server
  image: primo-customizations-cdn-server
  build:
    context: ./
    cache_from:
      - primo-customizations-cdn-server
    dockerfile: Dockerfile.cdn-server

x-environment: &x-environment
  VIEW: ${VIEW}

x-build-primo-customization: &x-build-primo-customization
  image: primo-explore-devenv
  build:
    context: ./
    cache_from:
      - primo-explore-devenv
    dockerfile: Dockerfile

services:
  bookmarklet:
    <<: [ *x-build-primo-customization ]
    command: yarn bookmarklet
    volumes:
      - ./tmp:/app/tmp
  cdn-server:
    <<: [*x-build-cdn-server]
    ports:
      - "3000:3000"
    # volumes:
    #   - ./cdn:/app/cdn
  create-package:
    <<: [*x-build-primo-customization]
    command: yarn primo-explore-devenv:create-package $VIEW
    environment:
      <<: *x-environment
    # volumes:
    #   - ./custom:/app/custom
    #   - ./primo-explore-devenv/packages/:/app/primo-explore-devenv/packages
  # TODO: What's the best way to get the file out of the container?
  eslint-cjs-file:
    <<: [ *x-build-primo-customization ]
    command: yarn eslint:cjs-file
  # TODO: What's the best way to get the files at the root of project out of the container?
  eslint-fix:
      <<: [ *x-build-primo-customization ]
      command: yarn eslint:fix
      volumes:
        - ./cdn:/app/cdn
        - ./custom:/app/custom
        - ./scripts:/app/scripts
        - ./tools:/app/tools
  generate-custom-directives:
    <<: [ *x-build-primo-customization ]
    command: yarn generate-custom-directives
    volumes:
      - ./custom:/app/custom
  primo-explore-devenv:
    <<: [*x-build-primo-customization]
    command: yarn primo-explore-devenv:run $VIEW
    depends_on:
      - cdn-server
    environment:
      <<: *x-environment
    ports:
      - "8003:8003"
    # volumes:
    #   - ./custom:/app/custom
