version: "3.8"

x-cdn-volume: &x-cdn-volume
  volumes:
    - ./cdn:/app/cdn

x-build-cdn-server: &x-build-cdn-server
  image: primo-customizations-cdn-server
  build:
    context: ./
    cache_from:
      - primo-customizations-cdn-server
    dockerfile: Dockerfile.cdn-server

x-build-primo-customization: &x-build-primo-customization
  image: primo-explore-devenv
  build:
    context: ./
    cache_from:
      - primo-explore-devenv
    dockerfile: Dockerfile

services:
  cdn-server:
    <<: [*x-build-cdn-server, *x-cdn-volume]
    ports:
      - "3000:3000"
    # volumes:
    #  - ./primo-explore-devenv/primo-explore/cdn:/app/primo-explore-devenv/primo-explore/cdn
  create-package:
    <<: [*x-build-primo-customization]
    command: yarn primo-explore-devenv:create-package
    # volumes:
    #  - ./primo-explore-devenv/primo-explore/custom:/app/primo-explore-devenv/primo-explore/custom
    #  - ./primo-explore-devenv/packages/:/app/primo-explore-devenv/packages
  primo-explore-devenv:
    <<: [*x-build-primo-customization]
    depends_on:
      - cdn-server
    ports:
      - "8003:8003"
    # volumes:
    #  - ./primo-explore-devenv/primo-explore/custom:/app/primo-explore-devenv/primo-explore/custom
