version: "3.8"

x-build-cdn-server: &x-build-cdn-server
  image: primo-customization-cdn-server
  build:
    context: ./
    cache_from:
      - primo-customization-cdn-server
    dockerfile: Dockerfile.cdn-server

x-build-e2e: &x-build-e2e
  image: primo-customization-e2e
  build:
    context: ./
    dockerfile: test/e2e/Dockerfile
    cache_from:
      - primo-customization-e2e

x-environment: &x-environment
  VIEW: ${VIEW}

x-build-primo-customization: &x-build-primo-customization
  image: primo-customization-devenv
  build:
    context: ./
    cache_from:
      - primo-customization-devenv
    dockerfile: Dockerfile

services:
  app-css:
    <<: [ *x-build-primo-customization ]
    command: yarn primo-explore-devenv:app-css $VIEW
    environment:
      <<: *x-environment
    # volumes:
    #   - ./custom:/app/custom
  bookmarklet:
    <<: [ *x-build-primo-customization ]
    command: yarn bookmarklet
    networks:
      - primo-customization-net
    volumes:
      - ./tmp:/app/tmp
  # NOTE: This service name is hard-coded into the view packages' `getCdn()` code.
  #       If changing this name, make sure to update that reference.
  cdn-server:
    <<: [*x-build-cdn-server]
    networks:
      - primo-customization-net
    ports:
      - "3000:3000"
    # volumes:
    #   - ./cdn:/app/cdn
  create-package:
    <<: [*x-build-primo-customization]
    command: yarn primo-explore-devenv:create-package $VIEW
    environment:
      <<: *x-environment
    # volumes:
    #   - ./custom:/app/custom
    #   - ./primo-explore-devenv/packages/:/app/primo-explore-devenv/packages
  curl:
    image: appropriate/curl
    networks:
      - primo-customization-net
  e2e:
    <<: *x-build-e2e
    command: tail -f /dev/null
    depends_on:
      - primo-explore-devenv
    environment:
      <<: *x-environment
      IN_CONTAINER: true
      PLAYWRIGHT_BASE_URL: http://primo-explore-devenv:8003/discovery/search
    # https://playwright.dev/docs/ci#docker
    # CI configurations > Docker
    # "Using --ipc=host is also recommended when using Chromium. Without it Chromium can run out of memory and crash."
    ipc: host
    networks:
      - primo-customization-net
  e2e-update-golden-files:
    <<: *x-build-e2e
    depends_on:
      - primo-explore-devenv
    environment:
      <<: *x-environment
      IN_CONTAINER: true
      PLAYWRIGHT_BASE_URL: http://primo-explore-devenv:8003/discovery/search
      UPDATE_GOLDEN_FILES: true
    # https://playwright.dev/docs/ci#docker
    # CI configurations > Docker
    # "Using --ipc=host is also recommended when using Chromium. Without it Chromium can run out of memory and crash."
    ipc: host
    networks:
      - primo-customization-net
    # volumes:
    #   - ./test/e2e/tests/golden:/e2e/tests/golden
  # TODO: What's the best way to get the file out of the container?
  eslint-cjs-file:
    <<: [ *x-build-primo-customization ]
    command: yarn eslint:cjs-file
  # TODO: What's the best way to get the files at the root of project out of the container?
  eslint-fix:
      <<: [ *x-build-primo-customization ]
      command: yarn eslint:fix
      volumes:
        - ./cdn:/app/cdn
        - ./custom:/app/custom
        - ./scripts:/app/scripts
        - ./tools:/app/tools
  generate-custom-directives:
    <<: [ *x-build-primo-customization ]
    command: yarn generate-custom-directives
    volumes:
      - ./custom:/app/custom
  # NOTE: This service name is hard-coded into the view packages' `getCdn()` code.
  #       If changing this name, make sure to update that reference.
  primo-explore-devenv:
    <<: [*x-build-primo-customization]
    command: yarn primo-explore-devenv:run $VIEW
    networks:
      - primo-customization-net
    depends_on:
      - cdn-server
    environment:
      <<: *x-environment
    ports:
      - "8003:8003"
    # volumes:
    #   - ./custom:/app/custom

networks:
  primo-customization-net:
    driver: bridge
