docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:20.10.6-dc-1.29.1-0
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

version: 2
jobs:
  build:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker
          command: |
            docker compose build

workflows:
  version: 2
  build:
    jobs:
    - build
