docker-defaults: &docker-defaults
  docker:
    - image: cimg/base:2023.07
  #working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

version: 2
jobs:
  build:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker
          command: |
            docker compose build
      - run:
          name: Sanity check: do devenv and cdn start?
          command: |
            scripts/sanity-check-test.sh
      - <<: *auth_quay
      - run:
          name: Setup custom environment variables
          command: echo 'export BRANCH_NO_SLASH="${CIRCLE_BRANCH//\//_}"' >> $BASH_ENV
      - run:
          name: Push images to quay
          command: |
            scripts/push-images-to-quay.sh

workflows:
  version: 2
  build:
    jobs:
    - build
