// Option 2 from:
//     https://thirdiron.atlassian.net/wiki/spaces/BrowZineAPIDocs/pages/79200260/Ex+Libris+Primo+Integration

app.controller( 'prmSearchResultAvailabilityLineAfterController', function( $scope, $rootScope ) {
    // Generic CDN-based customization stuff moved here from autogenerated directives file.
    const vm = this;

    vm.getPnx = () => {
        try {
            return vm.parentCtrl.item.pnx;
        } catch ( err ) {
            console.log( 'prmSearchResultAvailabilityLineAfter: error accessing `vm.parentCtrl.item.pnx`' );

            return null;
        }
    };

    vm.rootScope = $rootScope;
    vm.scope = $scope;

    // LibKey code
    window.browzine.primo.searchResult( $scope );
} );

app.component( 'prmSearchResultAvailabilityLineAfter', {
    bindings   : { parentCtrl: '<' },
    controller : 'prmSearchResultAvailabilityLineAfterController',
    // Generic CDN-based customization stuff moved here from autogenerated directives file.
    templateUrl: `${ cdnUrl }/html/prm-search-result-availability-line-after.html`,
} );
// ... End BrowZine - Primo Integration
